runtime: java17
instance_class: F1
entrypoint: java -Xmx512m -jar main/target/my-monolith.jar -Dapplication.production=true
includes:
  - secrets.yaml

inbound_services:
  - warmup
automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_idle_instances: 1
  max_instances: 1
